In [1]:
import pandas as pd
import numpy as np
import sklearn as skl

In [5]:
pd.read_csv("adhd200_preprocessed_phenotypics.tsv", sep="\t")

,ScanDir ID,Site,Gender,Age,Handedness,DX,Secondary Dx,ADHD Measure,ADHD Index,Inattentive,Hyper/Impulsive,IQ Measure,Verbal IQ,Performance IQ,Full2 IQ,Full4 IQ,Med Status,QC_Athena,QC_NIAK
0,2371032,3,0.0,10.73,1,0,NaN,2,47,55,43,1.0,121.0,119.0,NaN,122.0,1,1.0,1.0
1,2026113,3,0.0,12.99,1,1,NaN,2,90,89,78,1.0,122.0,108.0,NaN,106.0,1,1.0,1.0
2,3434578,3,0.0,8.12,1,0,NaN,2,42,42,43,1.0,85.0,98.0,NaN,89.0,1,1.0,1.0
3,8628223,3,0.0,10.81,1,0,Simple phobia,2,42,49,49,1.0,85.0,86.0,NaN,97.0,1,1.0,1.0
4,1623716,3,0.0,12.65,1,1,NaN,2,87,90,90,1.0,89.0,88.0,NaN,89.0,1,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
968,25008,7,1.0,15.90,1,3,NaN,NaN,NaN,NaN,NaN,2.0,127.0,105.0,NaN,117.0,2,1.0,1.0
969,25009,7,1.0,13.87,1,0,NaN,NaN,NaN,NaN,NaN,2.0,135.0,119.0,NaN,130.0,1,1.0,1.0
970,25012,7,0.0,15.04,1,3,NaN,NaN,NaN,NaN,NaN,2.0,95.0,88.0,NaN,90.0,2,1.0,1.0
971,25013,7,1.0,13.64,1,0,NaN,NaN,NaN,NaN,NaN,2.0,114.0,109.0,NaN,113.0,1,1.0,1.0
972,25014,7,1.0,13.72,1,3,NaN,NaN,NaN,NaN,NaN,2.0,103.0,103.0,NaN,104.0,2,1.0,1.0